In [1]:
import torch

In [2]:
# Scalar Example
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.shape

(tensor(7), 0, torch.Size([]))

In [3]:
# Vector Example
vector = torch.tensor([1, 2, 3, 4])
vector, vector.ndim, vector.shape

(tensor([1, 2, 3, 4]), 1, torch.Size([4]))

In [4]:
# Matrix Example
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 2,
 torch.Size([3, 3]))

In [6]:
# Tensor Example
TENSOR = torch.randn(size=(5, 4, 3))
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[ 1.0294e+00, -9.8761e-01,  1.6261e-01],
          [ 4.6901e-01, -1.2981e+00,  7.8155e-01],
          [-1.0295e+00,  4.6450e-01,  1.0987e+00],
          [ 6.4188e-01,  9.8771e-01, -6.9567e-01]],
 
         [[ 5.7548e-01,  1.4178e+00,  3.9961e-01],
          [ 1.1336e+00, -4.6318e-01,  4.3928e-01],
          [ 7.3273e-01, -6.9367e-01,  5.5714e-01],
          [ 6.2852e-01,  1.6313e-01,  2.1114e-01]],
 
         [[-2.5579e-01, -1.4317e+00,  1.3411e+00],
          [ 7.9232e-01,  2.1706e+00, -3.7009e-01],
          [-8.0306e-01,  1.6020e+00, -1.7405e-03],
          [ 2.2912e+00,  8.2581e-02,  1.1050e+00]],
 
         [[-6.3925e-01,  9.5087e-01,  7.2426e-01],
          [ 2.0805e+00, -3.6151e-01, -2.4769e-01],
          [ 9.6679e-01, -7.6274e-01, -1.2498e+00],
          [ 1.8104e+00, -5.6077e-01, -3.1554e-01]],
 
         [[ 1.2370e-01, -8.7513e-01,  7.6903e-01],
          [-5.9523e-01,  7.1280e-02,  6.2935e-01],
          [ 6.3018e-01, -9.8574e-01, -1.7330e+00],
          [ 9.0408e